### ISSUE TITLE
racer runs fine in terminal, crashes when run from emacs

### ISSUE THREAD

**Issue by ravarspath** [racer-rust/racer#1128]
I installed racer via cargo `+nightly install racer` and when I run  `RUST_BACKTRACE=full CARGO_HOME=/home/ryan/.cargo RUST_SRC_PATH=/home/ryan/Desktop/source/rust/src/ ~/.cargo/bin/racer find-definition 12 9 /home/ryan/Desktop/code/metamorpher/src/main.rs ` in the terminal

I get
```
MATCH with_ssl,106,11,/home/ryan/.cargo/registry/src/github.com-1ecc6299db9ec823/mailin-embedded-0.5.0/src/lib.rs,Function,pub fn with_ssl(&mut self, ssl_config: SslConfig) -> Result<&mut Self, Error>
END
```
and when run from emacs (via eshell).

```
RUST_BACKTRACE=full CARGO_HOME=/home/ryan/.cargo RUST_SRC_PATH=/home/ryan/Desktop/source/rust/src/ ~/.cargo/bin/racer find-definition 12 9 /home/ryan/Desktop/code/metamorpher/src/main.rs 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/ryan/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.1.37/src/racer/metadata.rs:51:58
stack backtrace:
   0:     0x562fecc80290 - std::backtrace_rs::backtrace::libunwind::trace::hdf911925cfd1a062
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x562fecc80290 - std::backtrace_rs::backtrace::trace_unsynchronized::h1a4f248df23e18fe
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x562fecc80290 - std::sys_common::backtrace::_print_fmt::hf3ec23fc59b676bd
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/sys_common/backtrace.rs:79
   3:     0x562fecc80290 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h00fdb223b1b833ac
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/sys_common/backtrace.rs:58
   4:     0x562fecca541c - core::fmt::write::h1857a60b204f1b6a
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/core/src/fmt/mod.rs:1082
   5:     0x562fecc7c757 - std::io::Write::write_fmt::ha851958ed267cb97
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/io/mod.rs:1514
   6:     0x562fecc825f0 - std::sys_common::backtrace::_print::hf25dbce5d8adc35c
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/sys_common/backtrace.rs:61
   7:     0x562fecc825f0 - std::sys_common::backtrace::print::h40243408d050ccf7
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/sys_common/backtrace.rs:48
   8:     0x562fecc825f0 - std::panicking::default_hook::{{closure}}::ha452abcc85cd3549
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/panicking.rs:208
   9:     0x562fecc8233c - std::panicking::default_hook::h637245b92cbb00b1
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/panicking.rs:227
  10:     0x562fecc82c53 - std::panicking::rust_panic_with_hook::h2f4c96dfd8ba524a
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/panicking.rs:577
  11:     0x562fecc82829 - std::panicking::begin_panic_handler::{{closure}}::h7740abbe2875cb4d
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/panicking.rs:484
  12:     0x562fecc8071c - std::sys_common::backtrace::__rust_end_short_backtrace::hcad001df0a36db28
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/sys_common/backtrace.rs:153
  13:     0x562fecc827e9 - rust_begin_unwind
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/panicking.rs:483
  14:     0x562fecca3cd1 - core::panicking::panic_fmt::hb15d6f55e8472f62
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/core/src/panicking.rs:85
  15:     0x562fecca3c1d - core::panicking::panic::h5d1c61fed2502a5f
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/core/src/panicking.rs:50
  16:     0x562fec9b3718 - racer::metadata::MetadataCache::setup::hea67954abb927d18
  17:     0x562fec9b3756 - <racer::metadata::MetadataCache as racer::project_model::ProjectModelProvider>::edition::h1ced1229b93cee40
  18:     0x562fec9b239d - racer::fileres::search_crate_names::h473091774e4db4cb
  19:     0x562fec9ffd50 - racer::nameres::resolve_name::h4d0c2e91c1bbbe80
  20:     0x562feca036b7 - racer::nameres::resolve_path::h4a5d8a7b407397f6
  21:     0x562feca037e4 - racer::nameres::resolve_path::h4a5d8a7b407397f6
  22:     0x562fec9a045f - racer::matchers::match_use::hcf51f865c8fe9ca9
  23:     0x562fec9fd872 - racer::nameres::run_matchers_on_blob::h1f97fba7b186722e
  24:     0x562fec9fb9e8 - racer::nameres::search_scope::ha05232833ac8eaaf
  25:     0x562fec9fec6d - racer::nameres::resolve_name::h4d0c2e91c1bbbe80
  26:     0x562feca036b7 - racer::nameres::resolve_path::h4a5d8a7b407397f6
  27:     0x562feca037e4 - racer::nameres::resolve_path::h4a5d8a7b407397f6
  28:     0x562fec9fdf46 - racer::nameres::resolve_path_with_primitive::h5a31b630c781d216
  29:     0x562fec96f2f9 - racer::ast::resolve_ast_path::h68f15a8a497cd783
  30:     0x562fec971135 - <racer::ast::ExprTypeVisitor as rustc_ap_rustc_ast::visit::Visitor>::visit_expr::h10bcd585d3cc0a23
  31:     0x562fec970402 - <racer::ast::ExprTypeVisitor as rustc_ap_rustc_ast::visit::Visitor>::visit_expr::h10bcd585d3cc0a23
  32:     0x562fec96ed09 - <racer::ast::LetTypeVisitor as rustc_ap_rustc_ast::visit::Visitor>::visit_local::hdb3b384a1b4323da
  33:     0x562fec9a9128 - scoped_tls::ScopedKey<T>::set::hff3059af58ecaea8
  34:     0x562fec94bbd7 - rustc_ap_rustc_ast::attr::with_session_globals::he6b74da8c1387718
  35:     0x562fec9be987 - racer::typeinf::get_type_of_match::h967d518b1573560a
  36:     0x562fec97124d - <racer::ast::ExprTypeVisitor as rustc_ap_rustc_ast::visit::Visitor>::visit_expr::h10bcd585d3cc0a23
  37:     0x562fec970a23 - <racer::ast::ExprTypeVisitor as rustc_ap_rustc_ast::visit::Visitor>::visit_expr::h10bcd585d3cc0a23
  38:     0x562fec9a5d9c - scoped_tls::ScopedKey<T>::set::h709c0578f99a41e4
  39:     0x562fec94b937 - rustc_ap_rustc_ast::attr::with_session_globals::h9da151184ef3301d
  40:     0x562fec974f5d - racer::ast::get_type_of::h4d7acbef5e4e982a
  41:     0x562fec949ecd - racer::core::find_definition_::h970329731a8bbe76
  42:     0x562fec941e39 - racer::core::find_definition::hba9a0c4c0b81b941
  43:     0x562fec93a51a - racer::run::hd05740677a6167c2
  44:     0x562fec939b93 - racer::main::he4ba5af56217fcd8
  45:     0x562fec92a043 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4fdab4b570622156
  46:     0x562fec9407d9 - std::rt::lang_start::{{closure}}::he832643f5196d381
  47:     0x562fecc83121 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h8f722aa2376c6c0c
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/core/src/ops/function.rs:259
  48:     0x562fecc83121 - std::panicking::try::do_call::ha1dfe904663a3f0a
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/panicking.rs:381
  49:     0x562fecc83121 - std::panicking::try::h31c41f6b45320048
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/panicking.rs:345
  50:     0x562fecc83121 - std::panic::catch_unwind::h314af947b95878bc
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/panic.rs:382
  51:     0x562fecc83121 - std::rt::lang_start_internal::hdcd0702c5eb5e187
                               at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/rt.rs:51
  52:     0x562fec93b352 - main
  53:     0x7f940fc55152 - __libc_start_main
  54:     0x562fec91909e - _start
  55:                0x0 - <unknown>
```

I am running manjaro 20.1 i3.

**Comment by ravarspath** [comment]
Just had to restart emacs
