### ISSUE TITLE
Main thread panic on find-definition inside string

### ISSUE THREAD

**Issue by draivin** [racer-rust/racer#429]
Platform: Windows 10 (Rust stable GNU 64-bit)

Test file:

```
fn main() {
    let a = "123456";
}
```

Command:
`racer find-definition 2 14 d:\test.rs`

Panic:

```
thread '<main>' panicked at 'assertion failed: begin <= end', ../src/libcore\str/mod.rs:1310
stack backtrace:
   0:           0xd23e9e - <unknown>
   1:           0xd20a82 - <unknown>
   2:           0xce80be - <unknown>
   3:           0xce8a2b - <unknown>
   4:           0xd20122 - <unknown>
   5:           0xd464c8 - <unknown>
   6:           0xd3f780 - <unknown>
   7:           0xd62b47 - <unknown>
   8:           0x42b14d - <unknown>
   9:           0x4e9205 - <unknown>
  10:           0x4ff9a7 - <unknown>
  11:           0x4f4cd0 - <unknown>
  12:           0x440ba4 - <unknown>
  13:           0x44472e - <unknown>
  14:           0x443fd4 - <unknown>
  15:           0x41533e - <unknown>
  16:           0x418f28 - <unknown>
  17:           0x4191e7 - <unknown>
  18:           0xd2add8 - <unknown>
  19:           0xd13fe3 - <unknown>
  20:           0xd2ace7 - <unknown>
  21:           0x419e3a - <unknown>
  22:           0x4013b4 - <unknown>
  23:           0x4014e7 - <unknown>
  24:     0x7ffdeefd2d91 - <unknown>
```

**Comment by phildawes** [comment]
Hi @Draivin 

Thanks for the issue, I can confirm. The full backtrace is 
```
thread '<main>' panicked at 'assertion failed: begin <= end', ../src/libcore/str/mod.rs:1310
stack backtrace:
   1:     0x7f465739f2f9 - sys::backtrace::tracing::imp::write::he18882fa84e6b00ePnt
   2:     0x7f465739e4d8 - panicking::on_panic::h495226a97f084523enx
   3:     0x7f46573906ae - sys_common::unwind::begin_unwind_inner::h7a4ee06c0d57e26affs
   4:     0x7f4657390e08 - sys_common::unwind::begin_unwind_fmt::hb590a1df1c16a800les
   5:     0x7f465739dd51 - rust_begin_unwind
   6:     0x7f46573cdd3f - panicking::panic_fmt::hc3363d565c1048da4HJ
   7:     0x7f46573c9f18 - panicking::panic::h14af70be4f3d4feaBGJ
   8:     0x7f46573d1cfe - str::slice_error_fail::hc530e48dc5ad1eab4UR
   9:     0x7f4656fda5a5 - str::traits::str.ops..Index<ops..Range<usize>>::index::ha6ebb7dc34ee218ciHR
                        at ../src/libcore/str/mod.rs:1129
  10:     0x7f4657090c43 - nameres::search_scope_headers::h52d59092010729a95Wd
                        at src/racer/nameres.rs:164
  11:     0x7f46570a7432 - nameres::search_local_scopes::h53e5b51387c93708ZTe
                        at src/racer/nameres.rs:721
  12:     0x7f465709c500 - nameres::resolve_name::h371d79fdd4f13a06mdf
                        at src/racer/nameres.rs:854
  13:     0x7f4656fef8fe - nameres::resolve_path::habdbda999d8b9e072of
                        at src/racer/nameres.rs:933
  14:     0x7f4656ff343c - core::find_definition_::h7d85254dfc45c4c9GZa
                        at src/racer/core.rs:487
  15:     0x7f4656ff2d8b - core::find_definition::hfe1fece70a8d73dfhZa
                        at src/racer/core.rs:461
  16:     0x7f4656fc444d - find_definition::h4ef0bd05e1434492Rra
                        at src/bin/main.rs:204
  17:     0x7f4656fc83cb - run::hef9019eeb6ab476bLBa
                        at src/bin/main.rs:283
  18:     0x7f4656fc86dc - main::ha4c9d7767f71aeff2Aa
                        at src/bin/main.rs:271
  19:     0x7f46573a0fa4 - sys_common::unwind::try::try_fn::h4848098439110500489
  20:     0x7f465739dbb8 - __rust_try
  21:     0x7f46573a0c18 - rt::lang_start::hcf64c98c1a7c0031Zkx
  22:     0x7f4656fc9516 - main
  23:     0x7f46569b6ec4 - __libc_start_main
  24:     0x7f4656fb0458 - <unknown>
  25:                0x0 - <unknown>
An unknown error occurred
```
I will try and take a look soon

**Comment by Soaa-** [comment]
This panic also happens when find-definition is called inside a comment.

This is causing problems with RustyCode (https://github.com/saviorisdead/RustyCode) as it calls "find-definition" at the mouse cursor location when the Ctrl key is pressed. I understand that the extension could change its behavior to not call "find-definition" on strings and comments, but at the very least, Racer shouldn't panic in that case.

**Comment by Henning-K** [comment]
I'm also having this issue with racer panicking when used in conjunction with RustyCode in VS Code but it doesn't just happen when hovering over comments AND pressing Ctrl, but always when the editor reloads the file from disk (i assume), or just simply moving the mouse cursor over a comment (even when the editor window isn't focused).

(Win7, VSCode, RustyCode, Racer 1.2.9, Rust 1.8.0)
the error message is:

`thread 'searcher' panicked at 'assertion failed: begin <= end', ../src/libcore\str/mod.rs:1597
note: Run with 'RUST_BACKTRACE=1' for a backtrace.`

Also:
I can't find anything on how to run the command with that parameter for a backtrace, help would be very much appreciated.

**Comment by zummenix** [comment]
For this particular case found a problem here: https://github.com/phildawes/racer/blob/ca9418be3cb18c9c19cabc61dda22ffaa09220f9/src/racer/nameres.rs#L203
If `stmtstart` is greater than `scopestart`.
Workaround:
```rust
if stmtstart > scopestart {
    return Vec::new().into_iter()
}
```
I don't see that as a solution.
Maybe knowing people will help to solve this issue in a better way.

**Comment by kngwyu** [comment]
Closed since I can't reproduce in current version.
