### ISSUE TITLE
Racer causes emacs to hang

### ISSUE THREAD

**Issue by letheed** [racer-rust/racer#495]
Since the dependency update a few days ago (280ed93), I've had long hang (several seconds) and high CPU usage when using racer in emacs. Reverting to 1.2.2 (78c4a2a) solves that for the moment.
The hangs happen very often, almost continuously in chained calls in iterators. Switching the focus from emacs to another window and back is enough to trigger them.
I figure either one of the dependencies made a breaking change, or something failed silently before and it's not handled the same way anymore. So I don't know if the bug is in racer or one of its dependencies.
For ex, with the following code:

``` rust
fn main() {
    println!("{}", (1..).step_by(2).filter(|n| foo(n).nth(99).unwrap()));
}
```

racer 1.2.2:

```
$ racer complete 5 32 src/main.rs
PREFIX 25,32,step_by
bogofile:1:1: 1:2 error: unexpected token: `)`
bogofile:1 )
           ^
END
```

master:

```
$ racer complete 5 32 src/main.rs
PREFIX 25,32,step_by
error: internal compiler error: Error constructed but not emitted
thread 'searcher' panicked at 'explicit panic', /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.26.0/src/errors/mod.rs:261
stack backtrace:
   1:     0x5594dc76ca30 - sys::backtrace::tracing::imp::write::hf66cd359dc225f8a0nu
   2:     0x5594dc76f09b - panicking::default_handler::_<closure>::closure.42795
   3:     0x5594dc76ec64 - panicking::default_handler::h74bfdb4a758a82e9EFy
   4:     0x5594dc75e556 - sys_common::unwind::begin_unwind_inner::h9d3a2e7a2c681f25ygt
   5:     0x5594dc5d0294 - sys_common::unwind::begin_unwind::h15176745018326918295
                        at ../src/libstd/sys/common/unwind/mod.rs:227
   6:     0x5594dc5d205e - errors::DiagnosticBuilder<'a>.Drop::drop::ha4d6fbd2990bc835j1c
                        at /home/damien/src/lang/rust/racer/<std macros>:3
   7:     0x5594dc518e87 - ast::string_to_stmt::h40ce05a563db929dTAb
                        at src/racer/ast.rs:45
                        at src/racer/ast.rs:35
                        at src/racer/ast.rs:40
   8:     0x5594dc50d370 - ast::get_type_of::h6725c8bc12416f624Vc
                        at src/racer/ast.rs:931
   9:     0x5594dc50a0a6 - core::complete_from_file::hca51ea36db472dd7b3a
                        at src/racer/core.rs:590
  10:     0x5594dc4d9b1d - sys_common::unwind::try::try_fn::h11952191105366660056
                        at src/bin/main.rs:139
                        at src/bin/main.rs:105
                        at ../src/libstd/thread/mod.rs:277
                        at ../src/libstd/sys/common/unwind/mod.rs:153
  11:     0x5594dc76c008 - __rust_try
  12:     0x5594dc7695db - sys_common::unwind::try::inner_try::hcce19deda87812016ct
  13:     0x5594dc4daa75 - boxed::F.FnBox<A>::call_box::h15567707113264359767
                        at ../src/libstd/sys/common/unwind/mod.rs:123
                        at ../src/libstd/thread/mod.rs:277
                        at ../src/liballoc/boxed.rs:541
  14:     0x5594dc76dbc3 - sys::thread::Thread::new::thread_start::hff6465701ed07c9coCx
  15:     0x7f45f3d3e6a9 - start_thread
  16:     0x7f45f385ceec - clone
  17:                0x0 - <unknown>
ERROR:racer: Search thread paniced: Any
END
```

**Comment by crumblingstatue** [comment]
#494 is semi-related, as it also causes a hang in the same way.

I can confirm that this hang happens in various cases, not just #494 or #495.

**Comment by letheed** [comment]
Can't reproduce on racer 2.0.9.

Closing.
