### ISSUE TITLE
racer panic on string

### ISSUE THREAD

**Issue by letheed** [racer-rust/racer#496]
The following code:

``` rust
fn main {
    let f = File::open("tests/m256..257.txt").unwr
}
```

produces the following panic:

``` shell
$ racer complete 2 50 main.rs
PREFIX 46,50,unwr
bogofile:1:8: 1:10 error: unterminated double quote string
bogofile:1 257.txt")
                  ^~
thread 'searcher' panicked at 'Box<Any>', /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/parse/lexer/mod.rs:1117
stack backtrace:
   1:     0x55e27d260aa0 - sys::backtrace::tracing::imp::write::hb120982054a416e35nu
   2:     0x55e27d2630ab - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.42840
   3:     0x55e27d262d16 - panicking::default_handler::h7ae2e4523ef4c187IFy
   4:     0x55e27d25298c - sys_common::unwind::begin_unwind_inner::h5fb19481d14902dbDgt
   5:     0x55e27d1265ba - sys_common::unwind::begin_unwind::h11772222310432410183
                        at ../src/libstd/sys/common/unwind/mod.rs:236
   6:     0x55e27d1c4a7c - parse::lexer::StringReader<'a>::next_token_inner::hdcdff1aaac931df1Y3Q
                        at /home/damien/src/lang/rust/racer/<std macros>:3
   7:     0x55e27d1be2bb - parse::lexer::StringReader<'a>::advance_token::ha6797d50ae87f5a9DiQ
                        at /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/parse/lexer/mod.rs:240
   8:     0x55e27d15aeeb - parse::lexer::StringReader<'a>.Reader::next_token::h88596fc7d03833f3L8P
                        at /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/parse/lexer/mod.rs:89
   9:     0x55e27d064ea3 - parse::lexer::Reader::real_token::h6596309516582769722
                        at /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/parse/lexer/mod.rs:42
  10:     0x55e27d16478f - parse::parser::Parser<'a>::bump::ha00c42d7ab41c23fEUH
                        at /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/parse/parser.rs:931
  11:     0x55e27d18f43f - parse::parser::Parser<'a>::parse_dot_or_call_expr_with_::h030ace1b8ca06dbbRXJ
                        at /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/parse/parser.rs:600
                        at /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/parse/parser.rs:2365
  12:     0x55e27d18ee79 - parse::parser::Parser<'a>::parse_dot_or_call_expr_with::h4f237235460bb9e8AWJ
                        at /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/parse/parser.rs:2337
  13:     0x55e27d18edeb - parse::parser::Parser<'a>::parse_dot_or_call_expr::ha9e462b63474e4c6GVJ
                        at /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/parse/parser.rs:2327
  14:     0x55e27d19629c - parse::parser::Parser<'a>::parse_prefix_expr::h30cd0c408a98805eGqK
                        at /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/parse/parser.rs:2732
  15:     0x55e27d196d5d - parse::parser::Parser<'a>::parse_assoc_expr_with::h4e7e8d938422a3bcWxK
                        at /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/parse/parser.rs:2762
  16:     0x55e27d196bae - parse::parser::Parser<'a>::parse_assoc_expr::h98ef71aa3c8b56c7ExK
                        at /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/parse/parser.rs:2744
  17:     0x55e27d19a865 - parse::parser::Parser<'a>::with_res::h4088853774425238735
                        at /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/parse/parser.rs:3142
                        at /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/parse/parser.rs:3132
  18:     0x55e27d19dc31 - parse::parser::Parser<'a>::parse_stmt_::hd13368685556e957yRL
                        at /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/parse/parser.rs:3142
                        at /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/parse/parser.rs:3715
  19:     0x55e27d158b60 - parse::parser::Parser<'a>::parse_stmt::he1fd39eea6807f0e4QL
                        at /home/damien/.cargo/registry/src/github.com-88ac128001ac3a9a/syntex_syntax-0.24.0/src/parse/parser.rs:3593
  20:     0x55e27d06581d - ast::string_to_stmt::h97b83f10dc88bca1pAb
                        at src/racer/ast.rs:41
                        at src/racer/ast.rs:35
                        at src/racer/ast.rs:40
  21:     0x55e27d059f20 - ast::get_type_of::he411613ae284da4fAVc
                        at src/racer/ast.rs:931
  22:     0x55e27d056ce6 - core::complete_from_file::h6c723f023e66621bH2a
                        at src/racer/core.rs:588
  23:     0x55e27d026d8b - sys_common::unwind::try::try_fn::h11369264778982775646
                        at src/bin/main.rs:139
                        at src/bin/main.rs:105
                        at ../src/libstd/thread/mod.rs:277
                        at ../src/libstd/sys/common/unwind/mod.rs:127
  24:     0x55e27d26007b - __rust_try
  25:     0x55e27d25d69d - sys_common::unwind::inner_try::hf5df2c554f3d837dFdt
  26:     0x55e27d027e05 - boxed::F.FnBox<A>::call_box::h6173080581664821752
                        at ../src/libstd/sys/common/unwind/mod.rs:123
                        at ../src/libstd/thread/mod.rs:277
                        at ../src/liballoc/boxed.rs:541
  27:     0x55e27d261c03 - sys::thread::Thread::new::thread_start::h05e6a3d5b147b01bsCx
  28:     0x7f041187a6a9 - start_thread
  29:     0x7f0411398eec - clone
  30:                0x0 - <unknown>
ERROR:racer: Search thread paniced: Any
END
```

Obviously the double quoted string is terminated, so there's at least a problem in parsing.

**Comment by letheed** [comment]
Can't reproduce. Most likely solved by #545.
