### ISSUE TITLE
Don't panic about `RUST_SRC_PATH`

### ISSUE THREAD

**Issue by nrc** [racer-rust/racer#751]
I get see this a lot when using Racer via the RLS:

```
thread 'main' panicked at 'RUST_SRC_PATH is set: NotPresent', /checkout/src/libcore/result.rs:860
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:762
  11: racer::nameres::get_crate_file
             at /home/ncameron/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.9/src/racer/nameres.rs:737
  12: racer::nameres::resolve_name
             at /home/ncameron/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.9/src/racer/nameres.rs:1192
  13: racer::nameres::resolve_path
             at /home/ncameron/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.9/src/racer/nameres.rs:1294
  14: racer::nameres::resolve_path
             at /home/ncameron/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.9/src/racer/nameres.rs:1321
  15: racer::nameres::resolve_path
             at /home/ncameron/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.9/src/racer/nameres.rs:1321
  16: racer::matchers::match_use
             at /home/ncameron/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.9/src/racer/matchers.rs:582
  17: racer::matchers::match_types
             at /home/ncameron/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.9/src/racer/matchers.rs:38
  18: racer::nameres::run_matchers_on_blob
             at /home/ncameron/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.9/src/racer/nameres.rs:1038
  19: racer::nameres::search_scope
             at /home/ncameron/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.9/src/racer/nameres.rs:927
  20: racer::nameres::search_local_scopes
             at /home/ncameron/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.9/src/racer/nameres.rs:1075
  21: racer::nameres::resolve_name
             at /home/ncameron/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.9/src/racer/nameres.rs:1215
  22: racer::nameres::resolve_path
             at /home/ncameron/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.9/src/racer/nameres.rs:1294
  23: racer::core::complete_from_file_
             at /home/ncameron/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.9/src/racer/core.rs:965
  24: racer::core::complete_from_file
             at /home/ncameron/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.9/src/racer/core.rs:905
  25: rls::actions::ActionHandler::complete::{{closure}}
             at src/actions/mod.rs:263
  26: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:454
  27: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  28: std::panicking::try
             at /checkout/src/libstd/panicking.rs:433
  29: std::panic::catch_unwind
             at /checkout/src/libstd/panic.rs:361
  30: rls::actions::ActionHandler::complete
             at src/actions/mod.rs:256
  31: <rls::server::LsService<O>>::handle_message
             at src/server.rs:431
  32: <rls::server::LsService<O>>::run
             at src/server.rs:303
  33: rls::server::run_server
             at src/server.rs:615
  34: rls::main
             at src/main.rs:75
  35: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  36: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  37: main
  38: __libc_start_main
  39: _start
```

It would be nice if Racer coped gracefully with the env var in basically any state, rather than panicking.

**Comment by kngwyu** [comment]
Closed via #799 and #808
