### ISSUE TITLE
syntex_syntax-0.58.1 crash

### ISSUE THREAD

**Issue by Dushistov** [racer-rust/racer#786]
```
The last racer command was:

$ cd /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.58.1/
$ export CARGO_HOME=/home/evgeniy/.cargo
$ export RUST_SRC_PATH=/home/evgeniy/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src
$ /home/evgeniy/.cargo/bin/racer find-definition 365 29 /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.58.1/src/print/pprust.rs /tmp/racer27970QdX

This command terminated with exit code 101.

No output on stdout.

stderr:

thread 'main' panicked at 'Statement has a beginning', /checkout/src/libcore/option.rs:823
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::option::expect_failed
             at /checkout/src/libcore/option.rs:823
  10: racer::typeinf::get_type_of_match
             at /checkout/src/libcore/option.rs:302
             at src/racer/scopes.rs:76
             at src/racer/typeinf.rs:130
             at src/racer/typeinf.rs:278
  11: <core::option::Option<T>>::and_then
             at src/racer/ast.rs:535
             at /checkout/src/libcore/option.rs:605
  12: <racer::ast::ExprTypeVisitor<'c, 's> as syntex_syntax::visit::Visitor>::visit_expr
             at src/racer/ast.rs:530
  13: racer::ast::get_type_of
             at /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.52.0/src/visit.rs:618
             at src/racer/ast.rs:1109
  14: racer::core::find_definition_
             at src/racer/core.rs:1172
  15: racer::run
             at /home/evgeniy/projects/rust-infra/racer/src/racer/core.rs:1121
             at src/bin/main.rs:179
             at src/bin/main.rs:491
  16: racer::main
             at src/bin/main.rs:477
  17: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  18: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  19: __libc_start_main
  20: _start

The temporary file will have been deleted. You should be
able to reproduce the same output from racer with the
following command:

$ CARGO_HOME=/home/evgeniy/.cargo RUST_SRC_PATH=/home/evgeniy/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src /home/evgeniy/.cargo/bin/racer find-definition 365 29 /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.58.1/src/print/pprust.rs
```

**Comment by kngwyu** [comment]
Closed via #854
