### ISSUE TITLE
Racer panics with 'byte index 19610 is out of bounds' on autocompleting RgbImage type alias on image crate

### ISSUE THREAD

**Issue by cmteodoro** [racer-rust/racer#800]
On the image crate, there's this following type alias:

```rust
 type RgbImage = ImageBuffer<Rgb<u8>, Vec<u8>>;
```

Code that triggers the crash:

```rust
extern crate image;

use image::{ImageBuffer, RgbImage, Rgb};

fn main() {        
    let img : ImageBuffer<Rgb<u8>, Vec<u8>> = image::ImageBuffer::new(100,100); // Code completion works
    let img2 : RgbImage = image::ImageBuffer::new(100,100);  // Code completion doesn't work
}
```

When trying to autocomplete the variable `img` which uses the full type name, code completion works perfectly.

But when trying to autocomplete the variable `img2` which uses a type alias, as soon I hit the `.` button, Racer crashes.

Debug log and stacktrace:

```
DEBUG:racer::core: Field: contextstr is |img2|, searchstr is ||
DEBUG:racer::ast: visit_expr expr(4294967295: img2)
DEBUG:racer::ast: expr is a path P[img2]
DEBUG:racer::ast: resolve_ast_path P[img2]
DEBUG:racer::nameres: resolve_path_with_str P[img2]
DEBUG:racer::nameres: resolve_path P[img2] "/home/cmt/Test/src/main.rs" 261 ExactMatch
DEBUG:racer::nameres: resolve_name img2 "/home/cmt/Test/src/main.rs" 261 ExactMatch Both
DEBUG:racer::nameres: search_local_scopes PathSegment { name: "img2", types: [] } "/home/cmt/Test/src/main.rs" 261 ExactMatch Both
DEBUG:racer::nameres: searching scope Both start: 74 point: 261 'img2' "/home/cmt/Test/src/main.rs" ExactMatch local: true, session: Session { .. }
DEBUG:racer::matchers: match_pattern_let point is 167
DEBUG:racer::typeinf: get_type_of match Match ["img2", "/home/cmt/Test/src/main.rs", 167, true, Let, [], [] |let img2 : RgbImage = image::ImageBuffer::new(100,100);|] 
DEBUG:racer::typeinf: get_type_of_let_expr calling parse_let |let img2 : RgbImage = image::ImageBuffer::new(100,100);|
DEBUG:racer::ast: LetTypeVisitor: ty is Some(PathSearch(P[RgbImage], Scope ["/home/cmt/Test/src/main.rs", 167])). pos is 4, src is |let img2 : RgbImage = image::ImageBuffer::new(100,100);|
DEBUG:racer::ast: destructure_pattern_to_ty point 4 ty PathSearch(P[RgbImage], Scope ["/home/cmt/Test/src/main.rs", 167])    ||||||||    pat: pat(4294967295: img2)
DEBUG:racer::ast: destructure_pattern_to_ty matched an ident!
DEBUG:racer::ast: find_type_match P[RgbImage], "/home/cmt/Test/src/main.rs"
DEBUG:racer::nameres: resolve_path_with_str P[RgbImage]
DEBUG:racer::nameres: resolve_path P[RgbImage] "/home/cmt/Test/src/main.rs" 167 ExactMatch
DEBUG:racer::nameres: resolve_name RgbImage "/home/cmt/Test/src/main.rs" 167 ExactMatch Type
DEBUG:racer::nameres: search_local_scopes PathSegment { name: "RgbImage", types: [] } "/home/cmt/Test/src/main.rs" 167 ExactMatch Type
DEBUG:racer::nameres: searching scope Type start: 74 point: 167 'RgbImage' "/home/cmt/Test/src/main.rs" ExactMatch local: true, session: Session { .. }
DEBUG:racer::nameres: search_scope found matches ExactMatch []
DEBUG:racer::nameres: search_scope_headers for |RgbImage| pt: 73
DEBUG:racer::nameres: search_scope_headers preblock is |fn main() |
DEBUG:racer::nameres: search_fn_args: found start of fn!! 63 |impl blah {fn main() {}}| RgbImage
DEBUG:racer::nameres: searching scope Type start: 0 point: 167 'RgbImage' "/home/cmt/Test/src/main.rs" ExactMatch local: true, session: Session { .. }
DEBUG:racer::matchers: found use: RgbImage in |use image::{ImageBuffer, RgbImage, Rgb};|
DEBUG:racer::nameres: resolve_path P[image::RgbImage] "/home/cmt/Test/src/main.rs" 21 ExactMatch
DEBUG:racer::nameres: resolve_path P[image] "/home/cmt/Test/src/main.rs" 21 ExactMatch
DEBUG:racer::nameres: resolve_name image "/home/cmt/Test/src/main.rs" 21 ExactMatch Type
DEBUG:racer::nameres: search_local_scopes PathSegment { name: "image", types: [] } "/home/cmt/Test/src/main.rs" 21 ExactMatch Type
DEBUG:racer::nameres: searching scope Type start: 0 point: 21 'image' "/home/cmt/Test/src/main.rs" ExactMatch local: true, session: Session { .. }
DEBUG:racer::matchers: found an extern crate: |extern crate image;|
DEBUG:racer::matchers: extern crate image
DEBUG:racer::nameres: get_crate_file image, "/home/cmt/Test/src/main.rs"
DEBUG:racer::cargo: get_crate_file: from_path="/home/cmt/Test/src/main.rs"

[...]


DEBUG:racer::cargo: find_src_via_lockfile package_name: image
DEBUG:racer::nameres: get_crate_file  - found the crate file! "/home/cmt/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.16.0/src/lib.rs"
DEBUG:racer::nameres: searching a module 'image' for RgbImage (whole path: P[image::RgbImage])
DEBUG:racer::nameres: searching scope Both start: 0 point: 0 'RgbImage' "/home/cmt/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.16.0/src/lib.rs" ExactMatch local: false, session: Session { .. }
DEBUG:racer::matchers: found use: RgbImage in |pub use buffer::{
    Pixel,
    ConvertBuffer,
    // Image types
    ImageBuffer,
    RgbImage,
    RgbaImage,
    GrayImage,
    GrayAlphaImage
};|
DEBUG:racer::nameres: resolve_path P[buffer::RgbImage] "/home/cmt/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.16.0/src/lib.rs" 1059 ExactMatch
DEBUG:racer::nameres: resolve_path P[buffer] "/home/cmt/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.16.0/src/lib.rs" 1059 ExactMatch
DEBUG:racer::nameres: resolve_name buffer "/home/cmt/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.16.0/src/lib.rs" 1059 ExactMatch Type
DEBUG:racer::nameres: search_local_scopes PathSegment { name: "buffer", types: [] } "/home/cmt/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.16.0/src/lib.rs" 1059 ExactMatch Type
DEBUG:racer::nameres: searching scope Type start: 0 point: 1059 'buffer' "/home/cmt/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.16.0/src/lib.rs" ExactMatch local: true, session: Session { .. }
DEBUG:racer::matchers: found a module declaration: |mod buffer;|
DEBUG:racer::nameres: searching a module 'buffer' for RgbImage (whole path: P[buffer::RgbImage])
DEBUG:racer::nameres: searching scope Both start: 0 point: 0 'RgbImage' "/home/cmt/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.16.0/src/buffer.rs" ExactMatch local: false, session: Session { .. }
DEBUG:racer::matchers: found!! a type RgbImage
DEBUG:racer::nameres: resolve_path returning [Match ["RgbImage", "/home/cmt/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.16.0/src/buffer.rs", 19610, false, Type, [], [] |pub type RgbImage = ImageBuffer<Rgb<u8>, Vec<u8>>;|]]
DEBUG:racer::nameres: resolve_path returning [Match ["RgbImage", "/home/cmt/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.16.0/src/buffer.rs", 19610, false, Type, [], [] |pub type RgbImage = ImageBuffer<Rgb<u8>, Vec<u8>>;|]]
DEBUG:racer::ast: get_type_of_typedef match is Match ["RgbImage", "/home/cmt/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.16.0/src/buffer.rs", 19610, false, Type, [], [] |pub type RgbImage = ImageBuffer<Rgb<u8>, Vec<u8>>;|]
DEBUG:racer::ast: get_type_of_typedef blob string type RgbImage = ImageBuffer<Rgb<u8>, Vec<u8>>;
DEBUG:racer::ast: type type is P[ImageBuffer<P[Rgb<P[u8]>],P[Vec<P[u8]>]>]
DEBUG:racer::ast: typevisitor type is Some(P[ImageBuffer<P[Rgb<P[u8]>],P[Vec<P[u8]>]>])
DEBUG:racer::ast: get_type_of_typedef parsed type Some(P[ImageBuffer<P[Rgb<P[u8]>],P[Vec<P[u8]>]>])
thread 'main' panicked at 'byte index 19610 is out of bounds of `extern crate image;

use image::{ImageBuffer, RgbImage, Rgb};

fn main() {    
    let img : ImageBuffer<Rgb<u8>, Vec<u8>> = image::ImageBuffer::new(100,100);
    let img2 : RgbImage = image::ImageBuffer::new(100,100);  // Code completion doesn't work
    `[...]', /checkout/src/libcore/str/mod.rs:2226:8
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::str::slice_error_fail
             at /checkout/src/libcore/str/mod.rs:2226
  10: racer::scopes::mask_comments
  11: racer::scopes::scope_start
  12: racer::ast::find_type_match
  13: racer::ast::path_to_match
  14: <racer::ast::LetTypeVisitor<'c, 's> as syntex_syntax::visit::Visitor>::visit_local
  15: racer::ast::get_let_type
  16: racer::typeinf::get_type_of_match
  17: <core::option::Option<T>>::and_then
  18: <racer::ast::ExprTypeVisitor<'c, 's> as syntex_syntax::visit::Visitor>::visit_expr
  19: racer::ast::get_type_of
  20: racer::core::complete_from_file_
  21: racer::core::complete_from_file
  22: std::panicking::try::do_call
  23: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  24: <rls::server::LsService<O>>::dispatch_message
  25: rls::main
  26: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  27: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  28: __libc_start_main
  29: <unknown>
```

rls-preview 0.122.0-nightly (93b47d1 2017-09-25)
rustc 1.22.0-nightly (185cc5f26 2017-10-02)
cargo 0.23.0-nightly (e447ac7e9 2017-09-27)

**Comment by kngwyu** [comment]
Maybe it's because we just set wrong path to source, but now I'm feeling really difficult to debug this bug!
