### ISSUE TITLE
panick at 'Statement has a beginning' in one-line closure

### ISSUE THREAD

**Issue by Dushistov** [racer-rust/racer#856]
I use `racer 2.0.14`,
when I try put cursor at `v.to_str` and exec `M-x racer-find-definition` `racer panicked`

```Rust
extern crate walkdir;

use std::path::Path;
use walkdir::WalkDir;

fn boo() {
    let walker = WalkDir::new(Path::new("skia"))
        .follow_links(false)
        .into_iter();
    for entry in walker {
        let e = entry.unwrap_or_else(|err| panic!("walkdir entry error: {}", err));
        if e.file_type().is_file() {
            if let Some(Some(name)) = e.path().extension().map(|v| v.to_str()) {
                let name = name.to_lowercase();
                if name.ends_with("sit") || name.ends_with("map") {
                    println!("entry {:?}", e.path());
                }
            }
        }
    }
}
```
```sh
RUST_BACKTRACE=1 CARGO_HOME=/home/evgeniy/.cargo RUST_SRC_PATH=/home/evgeniy/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src /home/evgeniy/.cargo/bin/racer find-definition 13 70 /tmp/racer-bug/src/main.rs
thread 'main' panicked at 'Statement has a beginning', libcore/option.rs:916:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:72
   8: core::option::expect_failed
             at libcore/option.rs:916
   9: racer::typeinf::get_type_of_match
             at /checkout/src/libcore/option.rs:302
             at src/racer/scopes.rs:77
             at src/racer/typeinf.rs:130
             at src/racer/typeinf.rs:278
  10: <racer::ast::ExprTypeVisitor<'c, 's> as syntex_syntax::visit::Visitor>::visit_expr
             at src/racer/ast.rs:538
             at /checkout/src/libcore/option.rs:612
             at src/racer/ast.rs:533
  11: racer::ast::get_type_of
             at src/racer/ast.rs:1158
  12: racer::core::find_definition_
             at src/racer/core.rs:1194
  13: racer::core::find_definition
             at /home/evgeniy/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.0.14/src/racer/core.rs:1143
  14: racer::run
             at src/bin/main.rs:179
             at src/bin/main.rs:501
  15: racer::main
             at src/bin/main.rs:487
  16: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  17: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  18: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  19: std::rt::lang_start_internal
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  20: main
  21: __libc_start_main
  22: _start
/tmp/racer-bug/src $ 
```
I attached code with dummy crate that helps reproduce problem.

[racer-bug.zip](https://github.com/racer-rust/racer/files/2025541/racer-bug.zip)

**Comment by kngwyu** [comment]
Closed via #867
